#############################################################################
# Makefile for building: QtMath
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  QtMath.pro
# Template: app
# Command: /opt/dnv/ide/qt/5.2.1/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile QtMath.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/linux-g++ -I. -I/opt/dnv/ide/qt/5.2.1/gcc_64/include -I/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets -I/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui -I/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/dnv/ide/qt/5.2.1/gcc_64 -Wl,-rpath,/opt/dnv/ide/qt/5.2.1/gcc_64/lib
LIBS          = $(SUBLIBS) -lasound -L/opt/dnv/ide/qt/5.2.1/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/dnv/ide/qt/5.2.1/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		framepainter.cpp \
		sound.cpp moc_mainwindow.cpp \
		moc_framepainter.cpp
OBJECTS       = main.o \
		mainwindow.o \
		framepainter.o \
		sound.o \
		moc_mainwindow.o \
		moc_framepainter.o
DIST          = /opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/unix.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/linux.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/qconfig.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qt.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/resources.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/moc.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/uic.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/lex.prf \
		QtMath.pro \
		QtMath.pro
QMAKE_TARGET  = QtMath
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = QtMath


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9][^0-9]*\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: QtMath.pro /opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf /opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/unix.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/linux.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/qconfig.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/default_post.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qt.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/resources.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/moc.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/uic.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/unix/thread.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/yacc.prf \
		/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/lex.prf \
		QtMath.pro \
		/opt/dnv/ide/qt/5.2.1/gcc_64/lib/libQt5Widgets.prl \
		/opt/dnv/ide/qt/5.2.1/gcc_64/lib/libQt5Gui.prl \
		/opt/dnv/ide/qt/5.2.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile QtMath.pro
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/spec_pre.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/shell-unix.conf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/unix.conf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/linux.conf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/gcc-base.conf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/g++-base.conf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/common/g++-unix.conf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/qconfig.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qt_functions.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qt_config.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/spec_post.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/default_pre.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/resolve_config.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/default_post.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qml_debug.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/declarative_debug.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/unix/gdb_dwarf_index.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/warn_on.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/qt.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/resources.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/moc.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/unix/opengl.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/uic.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/unix/thread.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/exceptions.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/yacc.prf:
/opt/dnv/ide/qt/5.2.1/gcc_64/mkspecs/features/lex.prf:
QtMath.pro:
/opt/dnv/ide/qt/5.2.1/gcc_64/lib/libQt5Widgets.prl:
/opt/dnv/ide/qt/5.2.1/gcc_64/lib/libQt5Gui.prl:
/opt/dnv/ide/qt/5.2.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile QtMath.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/QtMath1.0.0 || mkdir -p .tmp/QtMath1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QtMath1.0.0/ && $(COPY_FILE) --parents mainwindow.h framepainter.h sound.h .tmp/QtMath1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp framepainter.cpp sound.cpp .tmp/QtMath1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/QtMath1.0.0/ && (cd `dirname .tmp/QtMath1.0.0` && $(TAR) QtMath1.0.0.tar QtMath1.0.0 && $(COMPRESS) QtMath1.0.0.tar) && $(MOVE) `dirname .tmp/QtMath1.0.0`/QtMath1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QtMath1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp moc_framepainter.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_framepainter.cpp
moc_mainwindow.cpp: /opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QMainWindow \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobal.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qconfig.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmutex.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlogging.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qflags.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstring.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qchar.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiterator.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qisenum.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmargins.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrect.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsize.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpoint.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpalette.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcolor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qrgb.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpair.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qregexp.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qbrush.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvector.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qregion.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qline.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtransform.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qimage.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qhash.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfont.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcursor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvariant.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdebug.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlocale.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qset.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfile.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qicon.h \
		framepainter.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QWidget \
		sound.h \
		mainwindow.h
	/opt/dnv/ide/qt/5.2.1/gcc_64/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_framepainter.cpp: /opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QWidget \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobal.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qconfig.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmutex.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlogging.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qflags.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstring.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qchar.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiterator.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qisenum.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmargins.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrect.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsize.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpoint.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpalette.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcolor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qrgb.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpair.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qregexp.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qbrush.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvector.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qregion.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qline.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtransform.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qimage.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qhash.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfont.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcursor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvariant.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdebug.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlocale.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qset.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfile.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		framepainter.h
	/opt/dnv/ide/qt/5.2.1/gcc_64/bin/moc $(DEFINES) $(INCPATH) framepainter.h -o moc_framepainter.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/opt/dnv/ide/qt/5.2.1/gcc_64/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QMainWindow \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobal.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qconfig.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmutex.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlogging.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qflags.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstring.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qchar.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiterator.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qisenum.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmargins.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrect.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsize.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpoint.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpalette.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcolor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qrgb.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpair.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qregexp.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qbrush.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvector.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qregion.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qline.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtransform.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qimage.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qhash.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfont.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcursor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvariant.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdebug.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlocale.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qset.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfile.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qicon.h \
		framepainter.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QWidget \
		sound.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QApplication \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qapplication.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qeventloop.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qguiapplication.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QMainWindow \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qmainwindow.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobal.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qconfig.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmutex.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlogging.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qflags.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstring.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qchar.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiterator.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qisenum.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmargins.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrect.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsize.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpoint.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpalette.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcolor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qrgb.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpair.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qregexp.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qbrush.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvector.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qregion.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qline.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtransform.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qimage.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qhash.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfont.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcursor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvariant.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdebug.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlocale.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qset.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfile.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qtabwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qicon.h \
		framepainter.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QWidget \
		sound.h \
		ui_mainwindow.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QApplication \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qapplication.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qeventloop.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qguiapplication.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

framepainter.o: framepainter.cpp framepainter.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QWidget \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobal.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qconfig.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmutex.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlogging.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qflags.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstring.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qchar.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringbuilder.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qalgorithms.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiterator.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcoreevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qscopedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmetatype.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvarlengtharray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontainerfwd.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qisenum.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qobject_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmargins.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrect.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsize.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpoint.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpaintdevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpalette.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcolor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qrgb.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringlist.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdatastream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qiodevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qpair.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qregexp.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringmatcher.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qbrush.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvector.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qmatrix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpolygon.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qregion.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qline.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtransform.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpainterpath.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qimage.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpixmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qshareddata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qhash.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfont.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontmetrics.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qfontinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qcursor.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qkeysequence.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qevent.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qvariant.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qdebug.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtextstream.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlocale.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qset.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcontiguouscache.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurl.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qurlquery.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfile.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfiledevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qvector2d.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtouchdevice.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/QPainter \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpainter.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qtextoption.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qpen.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmath.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/QMouseEvent \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/QPoint \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/QApplication \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qapplication.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcoreapplication.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qeventloop.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qguiapplication.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o framepainter.o framepainter.cpp

sound.o: sound.cpp sound.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/QString \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstring.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qchar.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobal.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qconfig.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qfeatures.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsystemdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qprocessordetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qcompilerdetection.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qglobalstatic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qgenericatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_msvc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_integrity.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qoldbasicatomic.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_vxworks.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_power.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_alpha.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv7.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv6.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_armv5.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_bfin.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_ia64.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_mips.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_s390.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sh4a.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_sparc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_x86.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_gcc.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qatomic_unix.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qmutex.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qlogging.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qflags.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypeinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qtypetraits.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qsysinfo.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qbytearray.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qrefcount.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qnamespace.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qarraydata.h \
		/opt/dnv/ide/qt/5.2.1/gcc_64/include/QtCore/qstringbuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sound.o sound.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_framepainter.o: moc_framepainter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_framepainter.o moc_framepainter.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

